// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "lms-system-internship/entities"

	mock "github.com/stretchr/testify/mock"
)

// ChapterRepository is an autogenerated mock type for the ChapterRepository type
type ChapterRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ChapterRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx
func (_m *ChapterRepository) FindAll(ctx context.Context) ([]*entities.Chapter, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entities.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entities.Chapter, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entities.Chapter); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByCourseID provides a mock function with given fields: ctx, courseID
func (_m *ChapterRepository) FindByCourseID(ctx context.Context, courseID uint) ([]*entities.Chapter, error) {
	ret := _m.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for FindByCourseID")
	}

	var r0 []*entities.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]*entities.Chapter, error)); ok {
		return rf(ctx, courseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []*entities.Chapter); ok {
		r0 = rf(ctx, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *ChapterRepository) FindByID(ctx context.Context, id uint) (*entities.Chapter, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.Chapter, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.Chapter); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, chapter
func (_m *ChapterRepository) Save(ctx context.Context, chapter *entities.Chapter) error {
	ret := _m.Called(ctx, chapter)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Chapter) error); ok {
		r0 = rf(ctx, chapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, chapter
func (_m *ChapterRepository) Update(ctx context.Context, chapter *entities.Chapter) error {
	ret := _m.Called(ctx, chapter)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Chapter) error); ok {
		r0 = rf(ctx, chapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewChapterRepository creates a new instance of ChapterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChapterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChapterRepository {
	mock := &ChapterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
