// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "lms-system-internship/entities"

	mock "github.com/stretchr/testify/mock"
)

// CourseService is an autogenerated mock type for the CourseService type
type CourseService struct {
	mock.Mock
}

// CreateCourse provides a mock function with given fields: ctx, course
func (_m *CourseService) CreateCourse(ctx context.Context, course *entities.Course) error {
	ret := _m.Called(ctx, course)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Course) error); ok {
		r0 = rf(ctx, course)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCourse provides a mock function with given fields: ctx, courseID
func (_m *CourseService) DeleteCourse(ctx context.Context, courseID uint) error {
	ret := _m.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, courseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllCourses provides a mock function with given fields: ctx
func (_m *CourseService) GetAllCourses(ctx context.Context) ([]*entities.Course, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCourses")
	}

	var r0 []*entities.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entities.Course, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entities.Course); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCourse provides a mock function with given fields: ctx, courseID
func (_m *CourseService) GetCourse(ctx context.Context, courseID uint) (*entities.Course, error) {
	ret := _m.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetCourse")
	}

	var r0 *entities.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.Course, error)); ok {
		return rf(ctx, courseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.Course); ok {
		r0 = rf(ctx, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCourseDetails provides a mock function with given fields: ctx, course
func (_m *CourseService) UpdateCourseDetails(ctx context.Context, course *entities.Course) error {
	ret := _m.Called(ctx, course)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCourseDetails")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Course) error); ok {
		r0 = rf(ctx, course)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCourseService creates a new instance of CourseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseService {
	mock := &CourseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
